spring:
  web:
    cors:
      allowed-origins: "http://localhost:3000, https://your-frontend-domain.com" # Add your frontend domain here
      allowed-methods: GET, POST, PUT, DELETE, PATCH
      allowed-headers: "*"
      allow-credentials: true

  datasource:
    url: jdbc:postgresql://localhost:5432/Apple_db
    username: postgres
    password: heyaksh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
