spring:
  datasource:
    url: jdbc:h2:mem:Apple_db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    #properties:
      #hibernate:
        #format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE